# Generated by Django 3.1.4 on 2021-01-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
            },
        ),
    ]
