# Generated by Django 3.1.4 on 2021-01-20 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210120_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
