# Generated by Django 3.1.4 on 2021-01-12 00:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210109_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
        migrations.CreateModel(
            name='PostComent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=120, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, verbose_name='Direccion de email')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('texto', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.post')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
