# Generated by Django 3.1.4 on 2021-01-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210111_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcoment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='postcoment',
            name='texto',
            field=models.CharField(max_length=250),
        ),
    ]
