# Generated by Django 3.1.4 on 2021-01-18 02:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210113_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcoment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
