# Generated by Django 3.1.4 on 2021-01-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recursos', verbose_name='Imagen de portada'),
        ),
    ]
