# Generated by Django 3.1.4 on 2021-01-20 20:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_auto_20210118_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='EnvioRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('recurso_enviado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviados', to='recursos.recurso')),
            ],
        ),
    ]
