# Generated by Django 3.1.4 on 2021-01-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_auto_20210120_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_recursos'),
        ),
    ]
