# Generated by Django 3.1.4 on 2021-01-21 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_recurso_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviorecurso',
            name='recurso_enviado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enviados', to='recursos.recurso'),
        ),
    ]
